### ISSUE TITLE
Intro Lesson 1

### ISSUE THREAD

**Issue by smiya10** [smiya10/PyInterim#2]
I would like to point out that the first Intro lesson claims that multiply a number by a sentence will give an
error in Python. I would like to point out that this is not true. In Python, it is _perfectly legal_ to multiply integers and sentences. It is _not_ legal to multiply a float by a sentence as that just doesn't make sense.
Welcome to Python.

**Comment by hdamron17** [comment]
Added it as a footnote in case they want to know the dark side. Thanks.
